### ISSUE TITLE
ROCKET SPEED!  🚀🚀🚀

### ISSUE THREAD

**Issue by jcyuan** [phaserjs/phaser4-dev#1]
excited and also astonished, this is so fast 'cause I'm still not 100% familair with Phaser3 yet...
but I'm sure the architecture for Phaser4 will be more mature and intresting, hope to see him soon, and thanks for your effort as alwasy. 👍

**Comment by Weedshaker** [comment]
I just wish that they gonna use inline TypeScript (https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html)

**Comment by photonstorm** [comment]
We already use the `@type`, `@param` etc fields in our JSDocs, which will move over to our TS files, so I can't see why this wouldn't work. I thought `--checkJs` was only needed if you consume js files into your TS project? There aren't any js files in v4.
